"""empty message

Revision ID: 98fd243117e5
Revises: 4147ac2d01b6
Create Date: 2023-10-10 21:08:16.251274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98fd243117e5'
down_revision = '4147ac2d01b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subs', schema=None) as batch_op:
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
