"""added new PasswordResetSession table

Revision ID: ac297446bb85
Revises: 98fd243117e5
Create Date: 2025-03-30 14:18:17.735413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac297446bb85'
down_revision = '98fd243117e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reset_password_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=25), nullable=True),
    sa.Column('expiry_time', sa.Integer(), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reset_password_session')
    # ### end Alembic commands ###
